[build]
base = "/"
publish = "frontend/build"
command = "cd frontend && npm install && CI=false npm run build"

[functions]
directory = "api/functions"
node_bundler = "esbuild"
included_files = ["api/utils/**"]

[[redirects]]
from = "/.netlify/functions/vpc-list"
to = "/.netlify/functions/vpc-list"
status = 200
force = true
methods = ["GET", "OPTIONS"]

[[redirects]]
from = "/.netlify/functions/subnet-list"
to = "/.netlify/functions/subnet-list"
status = 200
force = true
methods = ["GET", "OPTIONS"]

[[redirects]]
from = "/.netlify/functions/subnet-generate"
to = "/.netlify/functions/subnet-generate"
status = 200
force = true
methods = ["POST", "OPTIONS"]

[[redirects]]
from = "/.netlify/functions/route-table-generate"
to = "/.netlify/functions/route-table-generate"
status = 200
force = true
methods = ["POST", "OPTIONS"]

[[redirects]]
from = "/.netlify/functions/igw-generate"
to = "/.netlify/functions/igw-generate"
status = 200
force = true
methods = ["POST", "OPTIONS"]

[[redirects]]
from = "/.netlify/functions/nat-generate"
to = "/.netlify/functions/nat-generate"
status = 200
force = true
methods = ["POST", "OPTIONS"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "18"

