[build]
  base = "/"
  publish = "frontend/build"
  command = "cd frontend && export NODE_OPTIONS=--openssl-legacy-provider && npm install && npm run build"

[functions]
  directory = "api/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

