[build]
base = "/"
publish = "frontend/build"
command = "cd frontend && npm install && CI=false npm run build"

[functions]
directory = "api/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/.netlify/functions/*"
to = "/.netlify/functions/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[build.environment]
NODE_VERSION = "18"

